create database finance;
use finance;
create table company (name varchar(30), symbol varchar(30));

create table industry (sector_number int, industry varchar(50), day_price_change decimal(30, 3), market_cap varchar(30), price_to_earnings_ratio decimal(30, 3), roe_percent decimal(30, 3), div_yield_percent varchar(30), debt_to_equity varchar(30), price_to_book decimal(30, 3), net_profit_margin decimal(30, 3), price_to_free_cash_flow decimal(30, 3), curr_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

create table sector (sector varchar(50), day_price_change decimal(30, 3), market_cap varchar(30), price_to_earnings_ratio decimal(30, 3), roe_percent decimal(30, 3), div_yield_percent varchar (30), debt_to_equity varchar(30), price_to_book decimal(30, 3), net_profit_margin decimal(30, 3), price_to_free_cash_flow decimal(30, 3), curr_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

create table companies (name varchar(50), day_price_change decimal(30, 3), market_cap varchar(30), price_to_earnings_ratio decimal(30, 3), roe_percent decimal(30, 3), div_yield_percent varchar(30), debt_to_equity varchar(30), price_to_book decimal(30, 3), net_profit_margin decimal(30, 3), price_to_free_cash_flow decimal(30, 3), curr_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

create table quotes (latest_value varchar(30), previous_close varchar(30), after_hours_change_realtime varchar(30), annualized_gain varchar(30), ask varchar(30), ask_Realtime varchar(30), ask_size varchar(30), average_daily_value varchar(30), bid varchar(30), bid_realtime varchar(30), bid_size varchar(30), book_value_per_share varchar(30), changeQuote varchar(30), change_in_percent varchar(30), changeFromFiftydayMovingAverage varchar(30), changeFromTwoHundredDayMovingAverage varchar(30), changeFromYearHigh varchar(30), changeFromYearlow varchar(30), changeInPercent varchar(30), changeInPercentRealtime varchar(30), changeRealtime varchar(30), commission varchar(30), currency varchar(30), daysHigh varchar(30), daysLow varchar(30), daysRange varchar(30), daysRangeRealtime varchar(30), DaysValueChange varchar(30), DaysValueChageRealtime varchar(30), dividendpaydate varchar(30), trailingannualdividendyield varchar(30), trailingannualdividendyieldInPrecent varchar(30), dilutedEPS varchar(30), EBITDA varchar(30), EPSEstimateCurrentYear varchar(30), EPSEstimateNextQuarter varchar(30), EPSEstimateNextYear varchar(30), ExDivedendNextYear varchar(30), exDividentDate varchar(30), fiftydaymovingaverage varchar(30), sharesfloat varchar(30), highlimit varchar(30), holdingsgain varchar(30), holdingsgainpercent varchar(30), holdingsgainpercentrealtime varchar(30), holdingsgainrealtime varchar(30), holdingsvalue varchar(30), holdingsvaluerealtime varchar(30), lasttradedate varchar(30), lasttradepriceonly varchar(30), lasttraderealtimewithtime varchar(30), lasttradesize varchar(30), lasttradetime varchar(30), lasttradewithtime varchar(30), lowlimit varchar(30), marketcapitalization varchar(30), marketcaprealtime varchar(30), moreinfo varchar(30), name varchar(30), notes varchar(30), oneyrtargetprice varchar(30), open varchar(30), orderbookrealtime varchar(30), pegratio varchar(30), peratio varchar(30), peratiorealtime varchar(30), percentchangefromfiftydaymovingaverage varchar(30), percentchangefromtwohundreddaymovingaverage varchar(30), changeinpercentfromyearhigh varchar(30), percentchangefromyearlow varchar(30), previousclose varchar(30), pricebook varchar(30), priceepsestimatecurrentyear varchar(30), priceepsestimatenextyear varchar(30), pricepaid varchar(30), pricesales varchar(30), revenue varchar(30), sharesowned varchar(30), sharesoutstanding varchar(30), shortratio varchar(30), stockexchange varchar(30), symbol varchar(30), tickertrend varchar(30), tradedate varchar(30), twohundredaymovingaverage varchar(30), volume varchar(30), yearhigh varchar(30), yearlow varchar(30), yearrange varchar(30), curr_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

#Not sure how to do treat historical quotes yet.

alter table company add column `id` int(10) unsigned primary KEY AUTO_INCREMENT;
alter table industry add column `id` int(10) unsigned primary KEY AUTO_INCREMENT;
alter table sector add column `id` int(10) unsigned primary KEY AUTO_INCREMENT;
alter table companies add column `id` int(10) unsigned primary KEY AUTO_INCREMENT;
alter table quotes add column `id` int(10) unsigned primary KEY AUTO_INCREMENT;
